[project]
name = "stack-queue-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "json5>=0.13.0",
    "pyinstaller>=6.19.0",
    "pyqt6>=6.10.2",
]
